-- CreateTable
CREATE TABLE "SiteSettings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "companyNameAr" TEXT NOT NULL,
    "companyNameEn" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "whatsapp" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "workingHours" TEXT NOT NULL,
    "companyDescription" TEXT NOT NULL,
    "commercialRegistration" TEXT,
    "taxNumber" TEXT,
    "heroTitle" TEXT NOT NULL,
    "heroText" TEXT NOT NULL,
    "heroPrimaryButtonText" TEXT NOT NULL,
    "heroPrimaryButtonUrl" TEXT NOT NULL,
    "heroSecondaryButtonText" TEXT NOT NULL,
    "heroSecondaryButtonUrl" TEXT NOT NULL,
    "heroTertiaryButtonText" TEXT NOT NULL,
    "heroTertiaryButtonUrl" TEXT NOT NULL,
    "heroImage" TEXT NOT NULL,
    "announcementText" TEXT NOT NULL,
    "showAnnouncement" BOOLEAN NOT NULL DEFAULT false,
    "logo" TEXT NOT NULL,
    "favicon" TEXT NOT NULL,
    "instagramUrl" TEXT,
    "xUrl" TEXT,
    "linkedinUrl" TEXT,
    "tiktokUrl" TEXT,
    "showFloatingWhatsapp" BOOLEAN NOT NULL DEFAULT true,
    "showContactDetails" BOOLEAN NOT NULL DEFAULT true,
    "footerDescription" TEXT NOT NULL,
    "copyrightText" TEXT NOT NULL,
    "showSocialLinks" BOOLEAN NOT NULL DEFAULT true,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "SiteSettings_singleton_check" CHECK ("id" = 1)
);

-- Create the single editable settings record from the current safe defaults.
INSERT INTO "SiteSettings" (
    "id",
    "companyNameAr",
    "companyNameEn",
    "phone",
    "whatsapp",
    "email",
    "city",
    "address",
    "workingHours",
    "companyDescription",
    "heroTitle",
    "heroText",
    "heroPrimaryButtonText",
    "heroPrimaryButtonUrl",
    "heroSecondaryButtonText",
    "heroSecondaryButtonUrl",
    "heroTertiaryButtonText",
    "heroTertiaryButtonUrl",
    "heroImage",
    "announcementText",
    "showAnnouncement",
    "logo",
    "favicon",
    "instagramUrl",
    "xUrl",
    "linkedinUrl",
    "tiktokUrl",
    "showFloatingWhatsapp",
    "showContactDetails",
    "footerDescription",
    "copyrightText",
    "showSocialLinks",
    "updatedAt"
) VALUES (
    1,
    '[أدخل الاسم العربي]',
    'ELITE WORLD',
    '[أدخل رقم الهاتف]',
    '[أدخل رقم واتساب]',
    '[أدخل البريد الإلكتروني]',
    '[أدخل المدينة]',
    '[أدخل العنوان]',
    '[أدخل ساعات العمل]',
    'معدات وحلول صناعية احترافية للمطاعم والمخابز والكافيهات والمشاريع الغذائية.',
    'نجهّز نجاحك بأعلى معايير الجودة',
    'معدات مطاعم ومخابز وحلول ستانلس ستيل احترافية، مصممة لتتحمل أقوى ظروف التشغيل اليومية.',
    'تصفح المعدات',
    '/shop',
    'اطلب عرض سعر',
    '/quote',
    'أرسل مخطط مشروعك',
    '/quote',
    '/images/hero-industrial-kitchen.png',
    'حلول معدات صناعية متكاملة',
    false,
    '/brand/elite-world-logo.png',
    '/favicon.ico',
    '#',
    '#',
    '#',
    '#',
    true,
    true,
    'حلول صناعية متكاملة لمعدات المطاعم والمخابز والكافيهات، وتصنيع الستانلس وتجهيز المشاريع من الدراسة إلى التشغيل.',
    'جميع الحقوق محفوظة.',
    true,
    CURRENT_TIMESTAMP
);
